Signout route
alpha1-fit/alpha-pulse pull request #31
Opened 2023-04-27 21:55 UTC by csaument

2023-04-27 23:14 UTC, Genemichael25 requested changes

2023-04-27 23:14 UTC, Genemichael25 commented on app/javascript/components/App.js
> +        window.location.href = "/" // Not working
Not working?

2023-04-27 23:20 UTC, csaument commented on app/javascript/components/App.js
> +        window.location.href = "/" // Not working
It doesn't break the application, but it doesn't work as expected.

Both the register new user fetch request and the destroy session fetch request force the application to refresh upon completion of the asynchronous request. This clears out the state and ensures that everything aligns with current permissions. Although a redirect from the window object can be disruptive (ie a barely perceptible flicker), trying to force the components to re-render through hooks (useState or useEffect) did not provide the appropriate refresh.

This one just doesn't refresh for some reason. I didn't see any indication of why it's different, and we can add further research to the ice box.

2023-04-29 02:50 UTC, Genemichael25 approved these changes

2023-04-29 03:49 UTC, merged